import type { CitationContext } from './services/gemini';

export interface BluebookTestCase {
  id: number;
  prompt: string;
  expected: string;
  context: CitationContext;
}

export const BLUEBOOK_TEST_SUITE: BluebookTestCase[] = [
  { id: 1, prompt: "The DDC district court decision in the Carefirst case from 2019 after it got remanded.", expected: "Attias v. Carefirst, Inc., 365 F. Supp. 3d 1 (D.D.C. 2019).", context: 'litigation' },
  { id: 2, prompt: "The Vassiliades DC Court of Appeals privacy case from 1985.", expected: "Vassiliades v. Garfinckel's, 492 A.2d 580 (D.C. 1985).", context: 'litigation' },
  { id: 3, prompt: "The Carpenter Supreme Court case about cell site location info.", expected: "Carpenter v. United States, 585 U.S. 296 (2018).", context: 'litigation' },
  { id: 4, prompt: "DC consumer protection act unfair trade practices section.", expected: "D.C. Code § 28-3904 (LexisNexis 2024).", context: 'litigation' },
  { id: 5, prompt: "DC code section for breach notification requirements.", expected: "D.C. Code § 28-3852 (LexisNexis 2024).", context: 'litigation' },
  { id: 6, prompt: "Federal Computer Fraud and Abuse Act section 1030.", expected: "18 U.S.C. § 1030 (2018).", context: 'litigation' },
  { id: 7, prompt: "Federal Rule 26(b)(2)(B) about inaccessible ESI.", expected: "Fed. R. Civ. P. 26(b)(2)(B).", context: 'litigation' },
  { id: 8, prompt: "DC federal district local rule on electronic filing.", expected: "D.D.C. LCvR 5.4.", context: 'litigation' },
  { id: 9, prompt: "FTC safeguards rule section 314.1.", expected: "16 C.F.R. § 314.1 (2024).", context: 'litigation' },
  { id: 10, prompt: "Restatement second torts public disclosure section.", expected: "Restatement (Second) of Torts § 652D (Am. L. Inst. 1977).", context: 'litigation' },
  { id: 11, prompt: "The Spokeo case about standing for data breaches.", expected: "Spokeo, Inc. v. Robins, 578 U.S. 330 (2016).", context: 'litigation' },
  { id: 12, prompt: "The TransUnion credit reporting class action case.", expected: "TransUnion LLC v. Ramirez, 594 U.S. 413 (2021).", context: 'litigation' },
  { id: 13, prompt: "The Clapper surveillance standing case.", expected: "Clapper v. Amnesty Int'l USA, 568 U.S. 398 (2013).", context: 'litigation' },
  { id: 14, prompt: "Federal Wiretap Act statute section.", expected: "18 U.S.C. § 2511 (2018).", context: 'litigation' },
  { id: 15, prompt: "Stored Communications Act section 2701.", expected: "18 U.S.C. § 2701 (2018).", context: 'litigation' },
  { id: 16, prompt: "DC breach law definitions section.", expected: "D.C. Code § 28-3851 (LexisNexis 2024).", context: 'litigation' },
  { id: 17, prompt: "Federal Rule 34 on document production.", expected: "Fed. R. Civ. P. 34.", context: 'litigation' },
  { id: 18, prompt: "Federal Rule 37 sanctions for discovery violations.", expected: "Fed. R. Civ. P. 37.", context: 'litigation' },
  { id: 19, prompt: "FTC Act unfair practices section.", expected: "15 U.S.C. § 45 (2018).", context: 'litigation' },
  { id: 20, prompt: "HIPAA privacy rule citation.", expected: "45 C.F.R. § 164.502 (2024).", context: 'litigation' },
  { id: 21, prompt: "The Google Street View privacy case.", expected: "In re Google Inc. Street View Elec. Commc'ns Litig., 794 F. Supp. 2d 1067 (N.D. Cal. 2011).", context: 'litigation' },
  { id: 22, prompt: "Equifax data breach MDL case.", expected: "In re Equifax Inc. Customer Data Sec. Breach Litig., 362 F. Supp. 3d 1295 (N.D. Ga. 2019).", context: 'litigation' },
  { id: 23, prompt: "Yahoo data breach litigation case.", expected: "In re Yahoo! Inc. Customer Data Sec. Breach Litig., 313 F. Supp. 3d 1113 (N.D. Cal. 2018).", context: 'litigation' },
  { id: 24, prompt: "Target data breach litigation case.", expected: "In re Target Corp. Customer Data Sec. Breach Litig., 66 F. Supp. 3d 1154 (D. Minn. 2014).", context: 'litigation' },
  { id: 25, prompt: "Capital One breach case in Virginia.", expected: "In re Capital One Consumer Data Sec. Breach Litig., 488 F. Supp. 3d 374 (E.D. Va. 2020).", context: 'litigation' },
  { id: 26, prompt: "Federal Rule 12(b)(6) motion to dismiss.", expected: "Fed. R. Civ. P. 12(b)(6).", context: 'litigation' },
  { id: 27, prompt: "Federal Rule 23 class actions.", expected: "Fed. R. Civ. P. 23.", context: 'litigation' },
  { id: 28, prompt: "DC Court of Appeals rules civil procedure.", expected: "D.C. Ct. App. R. 1.", context: 'litigation' },
  { id: 29, prompt: "CFAA definition of protected computer.", expected: "18 U.S.C. § 1030(e)(2) (2018).", context: 'litigation' },
  { id: 30, prompt: "Electronic Communications Privacy Act.", expected: "Electronic Communications Privacy Act of 1986, Pub. L. No. 99-508, 100 Stat. 1848.", context: 'litigation' },
  { id: 31, prompt: "GDPR regulation citation.", expected: "Regulation (EU) 2016/679, 2016 O.J. (L 119) 1.", context: 'general' },
  { id: 32, prompt: "California Consumer Privacy Act.", expected: "Cal. Civ. Code § 1798.100 (West 2024).", context: 'litigation' },
  { id: 33, prompt: "Virginia Consumer Data Protection Act.", expected: "Va. Code Ann. § 59.1-575 (2024).", context: 'litigation' },
  { id: 34, prompt: "Maryland Personal Information Protection Act.", expected: "Md. Code Ann., Com. Law § 14-3504 (LexisNexis 2024).", context: 'litigation' },
  { id: 35, prompt: "FTC v. Wyndham case.", expected: "FTC v. Wyndham Worldwide Corp., 799 F.3d 236 (3d Cir. 2015).", context: 'litigation' },
  { id: 36, prompt: "LabMD FTC enforcement case.", expected: "LabMD, Inc. v. FTC, 894 F.3d 1221 (11th Cir. 2018).", context: 'litigation' },
  { id: 37, prompt: "Facebook data privacy case.", expected: "In re Facebook, Inc. Consumer Privacy User Profile Litig., 402 F. Supp. 3d 767 (N.D. Cal. 2019).", context: 'litigation' },
  { id: 38, prompt: "LinkedIn data scraping case.", expected: "hiQ Labs, Inc. v. LinkedIn Corp., 938 F.3d 985 (9th Cir. 2019).", context: 'litigation' },
  { id: 39, prompt: "Van Buren CFAA Supreme Court case.", expected: "Van Buren v. United States, 593 U.S. 374 (2021).", context: 'litigation' },
  { id: 40, prompt: "Riley cell phone search case.", expected: "Riley v. California, 573 U.S. 373 (2014).", context: 'litigation' },
  { id: 41, prompt: "Fourth Amendment Katz case.", expected: "Katz v. United States, 389 U.S. 347 (1967).", context: 'litigation' },
  { id: 42, prompt: "Jones GPS tracking case.", expected: "United States v. Jones, 565 U.S. 400 (2012).", context: 'litigation' },
  { id: 43, prompt: "DC circuit data breach standing case.", expected: "Attias v. Carefirst, Inc., 865 F.3d 620 (D.C. Cir. 2017).", context: 'litigation' },
  { id: 44, prompt: "Federal Trade Commission Act section 5.", expected: "15 U.S.C. § 45(a)(1) (2018).", context: 'litigation' },
  { id: 45, prompt: "Sarbanes-Oxley whistleblower section.", expected: "18 U.S.C. § 1514A (2018).", context: 'litigation' },
  { id: 46, prompt: "Federal Rule of Evidence 403.", expected: "Fed. R. Evid. 403.", context: 'litigation' },
  { id: 47, prompt: "Federal Rule of Evidence 901 authentication.", expected: "Fed. R. Evid. 901.", context: 'litigation' },
  { id: 48, prompt: "DC Superior Court civil rule 26.", expected: "D.C. Super. Ct. Civ. R. 26.", context: 'litigation' },
  { id: 49, prompt: "FTC data security enforcement policy statement.", expected: "FTC, Protecting Consumer Privacy in an Era of Rapid Change (2012).", context: 'litigation' },
  { id: 50, prompt: "DOJ cybercrime manual.", expected: "U.S. Dep't of Justice, Prosecuting Computer Crimes (2010).", context: 'litigation' },
];
